### ISSUE TITLE
restore not working.

### ISSUE THREAD

**Issue by siddhu07** [tbarbugli/cassandra_snapshotter#107]
Traceback (most recent call last):
  File "/usr/local/bin/cassandra-snapshotter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/main.py", line 284, in main
    restore_backup(args)
  File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/main.py", line 110, in restore_backup
    args.s3_bucket_name
TypeError: __init__() takes exactly 6 arguments (5 given)

this is what i get when i execute 
sudo cassandra-snapshotter --s3-bucket-name=bucket  --s3-base-path=cassandra --aws-access-key-id=XXXX --aws-secret-access-key=XXXX restore --keyspace oneg --target-hosts 172.31.54.113

EXTRA INFO:
i install using pip install cassandra_snapshotter

**Comment by tbarbugli** [comment]
you need to specify the task you want to execute (eg. backup)

**Comment by siddhu07** [comment]
i need to restore it. And i gave restore. even list is working fine for me.

**Comment by tbarbugli** [comment]
sorry I missed that, restore is not really supported by the tool. There is some code and support for backup restoration but some fiddling with the code is required.

**Comment by siddhu07** [comment]
if cassandra snapshotter does not support, is  there any other way to restore the data?.

**Comment by rsltrifork** [comment]
"restore is not really supported by the tool" 
Why use this tool then? Doesn't it make a lot more sense to do a FS-level snapshot? (asuming your data cassandra directory is on a separate volume, which it should be for any database)

**Comment by DoctorOgg** [comment]
im getting the same issue with the restore command, i understand this is still a work in progress, any idea of when this command cant at least grab the files from s3, so we can manually restore from that point?
