### ISSUE TITLE
undefined symbol: _PyErr_ReplaceException when snapshotting

### ISSUE THREAD

**Issue by ethan-riskiq** [tbarbugli/cassandra_snapshotter#115]
I'm getting the following error when attempting to snapshot to s3:

 ```[casslp2001.usw1] out: Traceback (most recent call last):
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/bin/cassandra-snapshotter-agent", line 7, in <module>
[casslp2001.usw1] out:     from cassandra_snapshotter.agent import main
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/cassandra_snapshotter/agent.py", line 3, in <module>
[casslp2001.usw1] out:     import boto
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/boto/__init__.py", line 27, in <module>
[casslp2001.usw1] out:     from boto.pyami.config import Config, BotoConfigLocations
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/boto/pyami/config.py", line 29, in <module>
[casslp2001.usw1] out:     from boto.compat import expanduser, ConfigParser, NoOptionError, NoSectionError, StringIO
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/boto/compat.py", line 52, in <module>
[casslp2001.usw1] out:     from boto.vendored.six.moves import filter, http_client, map, _thread, \
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/boto/vendored/six.py", line 203, in load_module
[casslp2001.usw1] out:     mod = mod._resolve()
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/boto/vendored/six.py", line 115, in _resolve
[casslp2001.usw1] out:     return _import_module(self.mod)
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/boto/vendored/six.py", line 82, in _import_module
[casslp2001.usw1] out:     __import__(name)
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib64/python2.7/httplib.py", line 80, in <module>
[casslp2001.usw1] out:     import mimetools
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib64/python2.7/mimetools.py", line 6, in <module>
[casslp2001.usw1] out:     import tempfile
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib64/python2.7/tempfile.py", line 32, in <module>
[casslp2001.usw1] out:     import io as _io
[casslp2001.usw1] out:   File "/opt/rh/python27/root/usr/lib64/python2.7/io.py", line 51, in <module>
[casslp2001.usw1] out:     import _io
[casslp2001.usw1] out: ImportError: /opt/rh/python27/root/usr/lib64/python2.7/lib-dynload/_io.so: undefined symbol: _PyErr_ReplaceException
``` 
Environment and commands look good, running thusly:
  ```scl enable python27 'cassandra-snapshotter -v --aws-access-key-id=secret --aws-secret-access-key=secret --s3-bucket-name="bucket" --s3-bucket-region=us-west-2 --s3-base-path=bucket_folder --s3-ssenc backup --hosts=casslp2001.usw1,casslp2002.usw1,casslp2003.usw1 --nodetool-path=/opt/cassandra/bin/nodetool --cassandra-conf-path=/opt/cassandra/conf/'``` 

any ideas what's missing here? here's the pip packages I've got:

 ```[root@casslp2001 ~]# scl enable python27 'pip list'
asn1crypto (0.22.0)
Babel (0.9.6)
bcrypt (3.1.3)
boto (2.48.0)
cassandra-snapshotter (1.0.0)
cffi (1.10.0)
cryptography (2.0.3)
docutils (0.11)
enum34 (1.1.6)
Fabric (1.14.0)
idna (2.6)
ipaddress (1.0.18)
Jinja2 (2.6)
MarkupSafe (0.11)
nose (1.3.0)
paramiko (2.2.1)
pip (8.1.2)
pyasn1 (0.3.4)
pycparser (2.18)
Pygments (1.5)
PyNaCl (1.1.2)
PyYAML (3.12)
setuptools (0.9.8)
simplejson (3.2.0)
six (1.10.0)
Sphinx (1.1.3)
SQLAlchemy (0.7.9)
virtualenv (13.1.0)
Werkzeug (0.8.3)
wheel (0.24.0)```

**Comment by ethan-riskiq** [comment]
figured it out, wrong python was being shim'd
