### ISSUE TITLE
Unable to take backup. MalformedXML error

### ISSUE THREAD

**Issue by sonal2890** [tbarbugli/cassandra_snapshotter#57]
Hi,
I am making following call but receiving MalformedXML error. Any idea, what i am missing?

cassandra-snapshotter --aws-access-key-id **** --aws-secret-access-key **** --s3-bucket-region ****  --s3-bucket-name **** --s3-base-path **** backup --hosts localhost --nodetool-path ~/cassandra/cassandra/bin/nodetool --cassandra-bin-dir ~/cassandra/cassandra/bin/ --user ubuntu --cassandra-conf-path ~/cassandra/cassandra/conf

Do i need to create any policy at s3 bucket side? Currently, i have not configured any policy with same. Any pointer here would be of great help. Thanks!

Output:
[localhost] out: lzop 1.03
[localhost] out: LZO library 2.06
[localhost] out: Copyright (C) 1996-2010 Markus Franz Xaver Johannes Oberhumer
[localhost] out: lzop: lzop.c:351: f_open: Assertion `ft->name[0]' failed.
[localhost] out: lzop: lzop.c:351: f_open: Assertion `ft->name[0]' failed.
[localhost] out: lzop: lzop.c:351: f_open: Assertion `ft->name[0]' failed.
[localhost] out: lzop: lzop.c:351: f_open: Assertion `ft->name[0]' failed.
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/usr/local/bin/cassandra-snapshotter-agent", line 9, in <module>
[localhost] out:     load_entry_point('cassandra-snapshotter==0.4.0', 'console_scripts', 'cassandra-snapshotter-agent')()
[localhost] out:   File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/agent.py", line 266, in main
[localhost] out:     args.incremental_backups
[localhost] out:   File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/agent.py", line 145, in put_from_manifest
[localhost] out:     for _ in pool.imap(upload_file, ((bucket, f, destination_path(s3_base_path, f), s3_ssenc, buffer_size) for f in files)):
[localhost] out:   File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
[localhost] out:     raise value
[localhost] out: boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request
[localhost] out: <Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>0056A9AE61068765</RequestId><HostId>PEIIsIHjnwy/331DR/DokeyFCWRIKqSxUcV/W31WXmNXmHYCiW5W4iZgF+bV5MvHZet6jx+ufIM=</HostId></Error>
[localhost] out: lzop: lzop.c:351: f_open: Assertion `ft->name[0]' failed.
[localhost] out:

**Comment by tbarbugli** [comment]
what OS and lzop version do you have on your cassandra node?
