### ISSUE TITLE
pkg_resources.DistributionNotFound: ecdsa>=0.11

### ISSUE THREAD

**Issue by higgsmass** [tbarbugli/cassandra_snapshotter#66]
How: followed installation instructions (apt reported successful installation)
What: I get the following error when i type in cassandra-snapshotter --help
| 
ubuntu@vsk01:~$ cassandra-snapshotter --help
Traceback (most recent call last):
  File "/usr/local/bin/cassandra-snapshotter", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: ecdsa>=0.11
|
Environment:
ubuntu@vsk01:~$ uname -a
Linux vsk01 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@vsk01:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

Dependencies listed:
ubuntu@vsk01:~$ pip show cassandra-snapshotter
---
Name: cassandra-snapshotter
Version: 0.4.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: argparse, fabric, boto

What is ecdsa and why is this dependency not met ? Thanks!

**Comment by higgsmass** [comment]
I fixed it. Turns out some old version was installed by distutils (I think this should be made aware)
Fix was to  (a) uninstall cassandra-snapshotter (sudo pip uninstall cassandra-snapshotter)
and reinstall.. pulled the right dependencies.
-------------------------------------------
  Running setup.py install for cassandra-snapshotter
  Found existing installation: ecdsa 0.10
    DEPRECATION: Uninstalling a distutils installed project (ecdsa) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling ecdsa-0.10:
      Successfully uninstalled ecdsa-0.10
  Running setup.py install for pycrypto
