### ISSUE TITLE
Restore keyspace fails

### ISSUE THREAD

**Issue by nikhilsgadre** [tbarbugli/cassandra_snapshotter#94]
I am getting following error during restore. Any idea what is causing this failure?

Traceback (most recent call last):
  File "/usr/local/bin/cassandra-snapshotter", line 9, in <module>
    load_entry_point('cassandra-snapshotter==1.0.0', 'console_scripts', 'cassandra-snapshotter')()
  File "/usr/local/lib/python2.7/site-packages/cassandra_snapshotter/main.py", line 284, in main
    restore_backup(args)
  File "/usr/local/lib/python2.7/site-packages/cassandra_snapshotter/main.py", line 110, in restore_backup
    args.s3_bucket_name
TypeError: __init__() takes exactly 6 arguments (5 given)

My restore command is as follows:
cassandra-snapshotter --s3-bucket-name=mybucket --s3-bucket-region=us-west-2 --s3-base-path=/backups --aws-access-key-id=accesskey --aws-secret-access-key=secretkey restore --snapshot-name=LATEST --keyspace=mykeyspace --hosts=host1 --target-hosts=host1

**Comment by tbarbugli** [comment]
how do you install the tool?

**Comment by nikhilsgadre** [comment]
The same way as described in "how to install"
pip install cassandra_snapshotter
sudo yum install lzop

**Comment by mvdheijd** [comment]
I can confirm that in the version installed via pip restoring a backup gives this error. Does the pull-request on improving restore solve this by any chance?

**Comment by kapilnayar** [comment]
any clues/ info on how to resolve this issue would be appreciated..

**Comment by omeega** [comment]
I installed it on pip too and restore doesn't work for me too  : 
Traceback (most recent call last):
  File "/usr/local/bin/cassandra-snapshotter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/main.py", line 284, in main
    restore_backup(args)
  File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/main.py", line 110, in restore_backup
    args.s3_bucket_name
TypeError: __init__() takes exactly 6 arguments (5 given)

**Comment by kapilnayar** [comment]
@omeega you need to look at the improve_restore branch.

**Comment by omeega** [comment]
@kapilnayar thx the improve_restore branch works good.

**Comment by jalvz** [comment]
this has been already fixed in master already, looks like. New version should be pushed to PYPI, because in the meantime installing it with `pip` is broken.

**Comment by siddhu07** [comment]
@omeega i too installed by pip and not working for me. Could you help me on how did you solved?

**Comment by omeega** [comment]
@siddhu07, I used the improve_restore branch. (https://github.com/tbarbugli/cassandra_snapshotter/network)
